AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
